<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>

<script>

export default {
  name: 'App',
  components: {
  }
}
</script>

<style>
@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');

body {
  padding: 0;
  margin: 0;
  font-family: 'Roboto', sans-serif;
}

/**
 * @license
 * Generated by Zeplin
 * Copyright (C) 2020 - present Zeplin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at

 *     http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

:root {
  --fill-primary-color-400: #739ef2;
  --fill-primary-color-500: #588aee;
  --fill-primary-color-600: #3c71dd;
  --fill-primary-color-200: #c0d5fe;
  --fill-primary-color-800: #0c2a66;
  --fill-primary-color-700: #1e4799;
  --fill-primary-color-300: #a8c5fd;
  --fill-greyscale-200: #dcdfe9;
  --fill-primary-color-900: #061b45;
  --fill-greyscale-700: #53555d;
  --fill-greyscale-300: #bec2ce;
  --fill-greyscale-800: #34353b;
  --fill-greyscale-400: #a3a6b0;
  --fill-greyscale-600: #6c6e76;
  --fill-primary-color-100: #dde9ff;
  --fill-greyscale-900: #26272c;
  --fill-greyscale-500: #85878f;
  --transperent-greyscale-48: rgba(108, 110, 118, 0.48);
  --transperent-greyscale-32: rgba(108, 110, 118, 0.32);
  --transperent-greyscale-40: rgba(108, 110, 118, 0.4);
  --transperent-greyscale-16: rgba(108, 110, 118, 0.16);
  --transperent-greyscale-24: rgba(108, 110, 118, 0.24);
  --fill-greyscale-1000: #1e1f23;
  --fill-greyscale-1100: #0a0a0c;
  --fill-red-100: #fedfde;
  --fill-greyscale-100: #f1f4ff;
  --fill-red-200: #f4bbb9;
  --fill-red-300: #f09d9a;
  --fill-red-400: #eb7e7a;
  --fill-red-500: #d8605c;
  --fill-red-600: #c64843;
  --fill-red-700: #a9312d;
  --fill-red-800: #82221f;
  --fill-red-900: #561411;
  --transperent-red-48: rgba(198, 72, 67, 0.48);
  --transperent-red-40: rgba(198, 72, 67, 0.4);
  --transperent-red-32: rgba(198, 72, 67, 0.32);
  --transperent-red-24: rgba(198, 72, 67, 0.24);
  --transperent-red-16: rgba(198, 72, 67, 0.16);
  --transperent-red-8: rgba(198, 72, 67, 0.08);
  --fill-green-500: #6bb485;
  --fill-green-600: #519d6c;
  --fill-green-700: #3d8958;
  --fill-green-900: #165b2f;
  --fill-green-800: #287544;
  --fill-green-400: #82ce9d;
  --fill-green-300: #9fe0b6;
  --fill-green-200: #c1e8cf;
  --fill-green-100: #e2f3e8;
  --transperent-green-48: rgba(81, 157, 108, 0.48);
  --transperent-green-40: rgba(81, 157, 108, 0.4);
  --transperent-green-32: rgba(81, 157, 108, 0.32);
  --transperent-green-24: rgba(81, 157, 108, 0.24);
  --transperent-green-16: rgba(81, 157, 108, 0.16);
  --transperent-green-8: rgba(81, 157, 108, 0.08);
  --transperent-primary-color-48: rgba(88, 138, 238, 0.48);
  --transperent-primary-color-32: rgba(88, 138, 238, 0.32);
  --transperent-primary-color-40: rgba(88, 138, 238, 0.4);
  --transperent-primary-color-16: rgba(88, 138, 238, 0.16);
  --transperent-primary-color-24: rgba(88, 138, 238, 0.24);
  --transperent-primary-color-8: rgba(88, 138, 238, 0.08);
  --other-color-yellowgreen: #b4d152;
  --other-color-mint: #62b4d6;
  --other-color-purple: #a15cc7;
}
</style>
